<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="2" total="8" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-09-11T10:15:38 IST" name="Suite" finished-at="2025-09-11T10:16:00 IST" duration-ms="21360">
    <groups>
    </groups>
    <test started-at="2025-09-11T10:15:38 IST" name="Test" finished-at="2025-09-11T10:16:00 IST" duration-ms="21360">
      <class name="testscript.LoginTest">
        <test-method is-config="true" signature="browserInitializer()[pri:0, instance:testscript.LoginTest@7fb4f2a9]" started-at="2025-09-11T10:15:38 IST" name="browserInitializer" finished-at="2025-09-11T10:15:42 IST" duration-ms="3362" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserInitializer -->
        <test-method retried="true" signature="verifyLoginWithValidCredentials()[pri:1, instance:testscript.LoginTest@7fb4f2a9]" started-at="2025-09-11T10:15:42 IST" name="verifyLoginWithValidCredentials" description="login with valid credentials" finished-at="2025-09-11T10:15:43 IST" duration-ms="1736" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login is not sucessfull expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login is not sucessfull expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at testscript.LoginTest.verifyLoginWithValidCredentials(LoginTest.java:24)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithValidCredentials -->
        <test-method is-config="true" signature="driverQuit(org.testng.ITestResult)[pri:0, instance:testscript.LoginTest@7fb4f2a9]" started-at="2025-09-11T10:15:44 IST" name="driverQuit" finished-at="2025-09-11T10:15:44 IST" duration-ms="383" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyLoginWithValidCredentials status=SKIP method=LoginTest.verifyLoginWithValidCredentials()[pri:1, instance:testscript.LoginTest@7fb4f2a9] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverQuit -->
        <test-method is-config="true" signature="quitAndClose()[pri:0, instance:testscript.LoginTest@7fb4f2a9]" started-at="2025-09-11T10:15:44 IST" name="quitAndClose" finished-at="2025-09-11T10:15:44 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitAndClose -->
        <test-method is-config="true" signature="browserInitializer()[pri:0, instance:testscript.LoginTest@7fb4f2a9]" started-at="2025-09-11T10:15:44 IST" name="browserInitializer" finished-at="2025-09-11T10:15:46 IST" duration-ms="1782" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserInitializer -->
        <test-method retried="true" signature="verifyLoginWithValidCredentials()[pri:1, instance:testscript.LoginTest@7fb4f2a9]" started-at="2025-09-11T10:15:46 IST" name="verifyLoginWithValidCredentials" description="login with valid credentials" finished-at="2025-09-11T10:15:46 IST" duration-ms="788" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login is not sucessfull expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login is not sucessfull expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at testscript.LoginTest.verifyLoginWithValidCredentials(LoginTest.java:24)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithValidCredentials -->
        <test-method is-config="true" signature="driverQuit(org.testng.ITestResult)[pri:0, instance:testscript.LoginTest@7fb4f2a9]" started-at="2025-09-11T10:15:46 IST" name="driverQuit" finished-at="2025-09-11T10:15:47 IST" duration-ms="419" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyLoginWithValidCredentials status=SKIP method=LoginTest.verifyLoginWithValidCredentials()[pri:1, instance:testscript.LoginTest@7fb4f2a9] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverQuit -->
        <test-method is-config="true" signature="quitAndClose()[pri:0, instance:testscript.LoginTest@7fb4f2a9]" started-at="2025-09-11T10:15:47 IST" name="quitAndClose" finished-at="2025-09-11T10:15:47 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitAndClose -->
        <test-method is-config="true" signature="browserInitializer()[pri:0, instance:testscript.LoginTest@7fb4f2a9]" started-at="2025-09-11T10:15:47 IST" name="browserInitializer" finished-at="2025-09-11T10:15:49 IST" duration-ms="2033" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserInitializer -->
        <test-method signature="verifyLoginWithValidCredentials()[pri:1, instance:testscript.LoginTest@7fb4f2a9]" started-at="2025-09-11T10:15:49 IST" name="verifyLoginWithValidCredentials" description="login with valid credentials" finished-at="2025-09-11T10:15:50 IST" duration-ms="706" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login is not sucessfull expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login is not sucessfull expected [https://groceryapp.uniqassosiates.com/admin] but found [https://groceryapp.uniqassosiates.com/admin/login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at testscript.LoginTest.verifyLoginWithValidCredentials(LoginTest.java:24)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithValidCredentials -->
        <test-method is-config="true" signature="driverQuit(org.testng.ITestResult)[pri:0, instance:testscript.LoginTest@7fb4f2a9]" started-at="2025-09-11T10:15:50 IST" name="driverQuit" finished-at="2025-09-11T10:15:50 IST" duration-ms="413" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyLoginWithValidCredentials status=FAILURE method=LoginTest.verifyLoginWithValidCredentials()[pri:1, instance:testscript.LoginTest@7fb4f2a9] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverQuit -->
        <test-method is-config="true" signature="quitAndClose()[pri:0, instance:testscript.LoginTest@7fb4f2a9]" started-at="2025-09-11T10:15:50 IST" name="quitAndClose" finished-at="2025-09-11T10:15:50 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitAndClose -->
        <test-method is-config="true" signature="browserInitializer()[pri:0, instance:testscript.LoginTest@7fb4f2a9]" started-at="2025-09-11T10:15:50 IST" name="browserInitializer" finished-at="2025-09-11T10:15:52 IST" duration-ms="1831" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserInitializer -->
        <test-method signature="verifyLoginWithValidUsernameInvalidpassword()[pri:2, instance:testscript.LoginTest@7fb4f2a9]" started-at="2025-09-11T10:15:52 IST" name="verifyLoginWithValidUsernameInvalidpassword" description="Login With Valid Username Invalid Password" finished-at="2025-09-11T10:15:53 IST" duration-ms="874" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithValidUsernameInvalidpassword -->
        <test-method is-config="true" signature="driverQuit(org.testng.ITestResult)[pri:0, instance:testscript.LoginTest@7fb4f2a9]" started-at="2025-09-11T10:15:53 IST" name="driverQuit" finished-at="2025-09-11T10:15:53 IST" duration-ms="293" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyLoginWithValidUsernameInvalidpassword status=SUCCESS method=LoginTest.verifyLoginWithValidUsernameInvalidpassword()[pri:2, instance:testscript.LoginTest@7fb4f2a9] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverQuit -->
        <test-method is-config="true" signature="quitAndClose()[pri:0, instance:testscript.LoginTest@7fb4f2a9]" started-at="2025-09-11T10:15:53 IST" name="quitAndClose" finished-at="2025-09-11T10:15:53 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitAndClose -->
        <test-method is-config="true" signature="browserInitializer()[pri:0, instance:testscript.LoginTest@7fb4f2a9]" started-at="2025-09-11T10:15:53 IST" name="browserInitializer" finished-at="2025-09-11T10:15:56 IST" duration-ms="2541" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserInitializer -->
        <test-method signature="verifyLoginWithInvalidUsernameValidpassword()[pri:3, instance:testscript.LoginTest@7fb4f2a9]" started-at="2025-09-11T10:15:56 IST" name="verifyLoginWithInvalidUsernameValidpassword" description="Login With Invalid Username Valid Password" finished-at="2025-09-11T10:15:56 IST" duration-ms="756" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithInvalidUsernameValidpassword -->
        <test-method is-config="true" signature="driverQuit(org.testng.ITestResult)[pri:0, instance:testscript.LoginTest@7fb4f2a9]" started-at="2025-09-11T10:15:56 IST" name="driverQuit" finished-at="2025-09-11T10:15:57 IST" duration-ms="257" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyLoginWithInvalidUsernameValidpassword status=SUCCESS method=LoginTest.verifyLoginWithInvalidUsernameValidpassword()[pri:3, instance:testscript.LoginTest@7fb4f2a9] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverQuit -->
        <test-method is-config="true" signature="quitAndClose()[pri:0, instance:testscript.LoginTest@7fb4f2a9]" started-at="2025-09-11T10:15:57 IST" name="quitAndClose" finished-at="2025-09-11T10:15:57 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitAndClose -->
        <test-method is-config="true" signature="browserInitializer()[pri:0, instance:testscript.LoginTest@7fb4f2a9]" started-at="2025-09-11T10:15:57 IST" name="browserInitializer" finished-at="2025-09-11T10:15:59 IST" duration-ms="2040" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserInitializer -->
        <test-method signature="verifyLoginWithInvalidUsernameInvalidpassword()[pri:4, instance:testscript.LoginTest@7fb4f2a9]" started-at="2025-09-11T10:15:59 IST" name="verifyLoginWithInvalidUsernameInvalidpassword" description="Login With Invalid Username Invalid Password" finished-at="2025-09-11T10:15:59 IST" duration-ms="781" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithInvalidUsernameInvalidpassword -->
        <test-method is-config="true" signature="driverQuit(org.testng.ITestResult)[pri:0, instance:testscript.LoginTest@7fb4f2a9]" started-at="2025-09-11T10:15:59 IST" name="driverQuit" finished-at="2025-09-11T10:16:00 IST" duration-ms="243" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyLoginWithInvalidUsernameInvalidpassword status=SUCCESS method=LoginTest.verifyLoginWithInvalidUsernameInvalidpassword()[pri:4, instance:testscript.LoginTest@7fb4f2a9] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverQuit -->
        <test-method is-config="true" signature="quitAndClose()[pri:0, instance:testscript.LoginTest@7fb4f2a9]" started-at="2025-09-11T10:16:00 IST" name="quitAndClose" finished-at="2025-09-11T10:16:00 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitAndClose -->
      </class> <!-- testscript.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
